spring.application.name=Dubb

spring.datasource.url=jdbc:h2:mem:Dubb-Database

spring.datasource.username=Lonely
spring.datasource.password=

logging.level.com.lonelys.Dubb=DEBUG
logging.level.org.hibernate.SQL=DEBUG

app.storage.root=Dubb/storage

spring.h2.console.enabled=true
